version: "3.2"
services: 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - /home/$USER/data/queues/rabbitmq/lab/data:/var/lib/rabbitmq
      - /home/$USER/data/queues/rabbitmq/lab/log:/var/log/rabbitmq
    networks:
      - rabbitmq_net
networks: 
  rabbitmq_net:
    driver: bridge