# Use postgres/example user/password credentials
version: '3.8'

services:

  psql-db:
    image: postgres
    restart: always
    volumes:
      - /home/$USER/data/databases/OldSQL/postgres/lab:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DagoKabel
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080